// flow-typed signature: 9c05dad67096fb87677529be4afa2579
// flow-typed version: <<STUB>>/react-native-sensor-manager_v0.1.10/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sensor-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sensor-manager' {
  declare module.exports: any;
}
