// flow-typed signature: bdbc3782e5fd972a79a0a6d7171a0fcb
// flow-typed version: <<STUB>>/webpack-node-server-plugin_v^0.2.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-node-server-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-node-server-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-node-server-plugin/src/child_process' {
  declare module.exports: any;
}

declare module 'webpack-node-server-plugin/src/index' {
  declare module.exports: any;
}

declare module 'webpack-node-server-plugin/src/node-server-plugin' {
  declare module.exports: any;
}

declare module 'webpack-node-server-plugin/src/process' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-node-server-plugin/index' {
  declare module.exports: $Exports<'webpack-node-server-plugin'>;
}
declare module 'webpack-node-server-plugin/index.js' {
  declare module.exports: $Exports<'webpack-node-server-plugin'>;
}
declare module 'webpack-node-server-plugin/src/child_process.js' {
  declare module.exports: $Exports<'webpack-node-server-plugin/src/child_process'>;
}
declare module 'webpack-node-server-plugin/src/index.js' {
  declare module.exports: $Exports<'webpack-node-server-plugin/src/index'>;
}
declare module 'webpack-node-server-plugin/src/node-server-plugin.js' {
  declare module.exports: $Exports<'webpack-node-server-plugin/src/node-server-plugin'>;
}
declare module 'webpack-node-server-plugin/src/process.js' {
  declare module.exports: $Exports<'webpack-node-server-plugin/src/process'>;
}
